### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kamronalexander** [PlayerNguyen/OptEco#8]
I dont know what's causing this error but here's the report.
https://pastebin.com/7VfCnEqX

**Comment by PlayerNguyen** [comment]
Hello @kamronalexander, looking at the log and seems like the issue it's your server has been crashed because out of memory, JVM,...Actually, sometime when I hit the /reload too much, It crashing unreasonably and I cannot explain why, that maybe from JVM and other things from Java, system and this error is not from any plugins but from your server. 
But now the plugins are still working fine or just re-crash?

**Comment by kamronalexander** [comment]
@PlayerNguyen It consistently crashes. My server isn't running out of memory it specifically states that it didn't. It's using a 1/2 of the total memory given to my server. I've talked to every developer I could and they all recommend that I talk to you because its SQL error.

**Comment by PlayerNguyen** [comment]
Hey @kamronalexander, v1.5b fixed more issue of SQL problem, can you update your plugin? If that problem still appear, leave a comment. Thanks for using my plugin.
